apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: direct
  orgId: 1
  url: http://prometheus-operated:9090
  isDefault: true
  jsonData:
    timeInterval: 15s
    severity_critical: "4"
    severity_high: "3"
    severity_warning: "2"
    severity_info: "1"
  version: 1
  editable: true
